export const BENEVOLENCE_VAULT_ABI = [
  {
    inputs: [
      { internalType: "address", name: "_impactToken", type: "address" },
      { internalType: "address", name: "_reputationLedger", type: "address" },
      { internalType: "address", name: "_stablecoin", type: "address" },
      { internalType: "address", name: "_oracleAddress", type: "address" },
      { internalType: "address", name: "_daoAdmin", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AccessControlBadConfirmation", type: "error" },
  { inputs: [{ internalType: "address", name: "account", type: "address" }, { internalType: "bytes32", name: "neededRole", type: "bytes32" }], name: "AccessControlUnauthorizedAccount", type: "error" },
  { inputs: [], name: "ECDSAInvalidSignature", type: "error" },
  { inputs: [{ internalType: "uint256", name: "length", type: "uint256" }], name: "ECDSAInvalidSignatureLength", type: "error" },
  { inputs: [{ internalType: "bytes32", name: "s", type: "bytes32" }], name: "ECDSAInvalidSignatureS", type: "error" },
  { inputs: [], name: "EnforcedPause", type: "error" },
  { inputs: [{ internalType: "bytes32", name: "eventId", type: "bytes32" }], name: "EventAlreadyProcessed", type: "error" },
  { inputs: [], name: "ExpectedPause", type: "error" },
  { inputs: [{ internalType: "uint256", name: "requested", type: "uint256" }, { internalType: "uint256", name: "available", type: "uint256" }], name: "InsufficientVaultBalance", type: "error" },
  { inputs: [], name: "InvalidAddress", type: "error" },
  { inputs: [], name: "InvalidOracleSignature", type: "error" },
  { inputs: [{ internalType: "string", name: "nonce", type: "string" }], name: "NonceAlreadyUsed", type: "error" },
  { inputs: [{ internalType: "uint256", name: "expiredAt", type: "uint256" }, { internalType: "uint256", name: "currentTime", type: "uint256" }], name: "PayloadExpired", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  { inputs: [{ internalType: "address", name: "token", type: "address" }], name: "SafeERC20FailedOperation", type: "error" },
  { inputs: [{ internalType: "uint256", name: "score", type: "uint256" }, { internalType: "uint256", name: "minimum", type: "uint256" }], name: "ScoreBelowMinimum", type: "error" },
  { inputs: [], name: "ZeroAmount", type: "error" },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "admin", type: "address" }, { indexed: false, internalType: "uint256", name: "amount", type: "uint256" }],
    name: "EmergencyWithdraw",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "donor", type: "address" }, { indexed: false, internalType: "uint256", name: "amount", type: "uint256" }, { indexed: false, internalType: "uint256", name: "totalPoolBalance", type: "uint256" }, { indexed: false, internalType: "uint256", name: "timestamp", type: "uint256" }],
    name: "FundsDeposited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint256", name: "oldMin", type: "uint256" }, { indexed: false, internalType: "uint256", name: "newMin", type: "uint256" }],
    name: "MinScoreUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "oldOracle", type: "address" }, { indexed: false, internalType: "address", name: "newOracle", type: "address" }],
    name: "OracleAddressUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "bytes32", name: "eventId", type: "bytes32" }, { indexed: true, internalType: "address", name: "volunteer", type: "address" }, { indexed: true, internalType: "address", name: "beneficiary", type: "address" }, { indexed: false, internalType: "uint256", name: "impactScore", type: "uint256" }, { indexed: false, internalType: "uint256", name: "tokenReward", type: "uint256" }, { indexed: false, internalType: "bytes32", name: "zkProofHash", type: "bytes32" }, { indexed: false, internalType: "bytes32", name: "eventHash", type: "bytes32" }, { indexed: false, internalType: "uint256", name: "timestamp", type: "uint256" }],
    name: "RewardReleased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "bytes32", name: "role", type: "bytes32" }, { indexed: true, internalType: "bytes32", name: "previousAdminRole", type: "bytes32" }, { indexed: true, internalType: "bytes32", name: "newAdminRole", type: "bytes32" }],
    name: "RoleAdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "bytes32", name: "role", type: "bytes32" }, { indexed: true, internalType: "address", name: "account", type: "address" }, { indexed: true, internalType: "address", name: "sender", type: "address" }],
    name: "RoleGranted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "bytes32", name: "role", type: "bytes32" }, { indexed: true, internalType: "address", name: "account", type: "address" }, { indexed: true, internalType: "address", name: "sender", type: "address" }],
    name: "RoleRevoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "volunteer", type: "address" }, { indexed: false, internalType: "uint256", name: "newScore", type: "uint256" }, { indexed: false, internalType: "uint256", name: "cumulativeScore", type: "uint256" }],
    name: "ReputationUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }],
    name: "Unpaused",
    type: "event",
  },
  { inputs: [], name: "DAO_ADMIN_ROLE", outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "DEFAULT_ADMIN_ROLE", outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "DONOR_ROLE", outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "ORACLE_ROLE", outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }], name: "deposit", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "to", type: "address" }, { internalType: "uint256", name: "amount", type: "uint256" }], name: "emergencyWithdraw", outputs: [], stateMutability: "nonpayable", type: "function" },
  {
    inputs: [],
    name: "getStats",
    outputs: [
      { internalType: "uint256", name: "deposited", type: "uint256" },
      { internalType: "uint256", name: "distributed", type: "uint256" },
      { internalType: "uint256", name: "eventsVerified", type: "uint256" },
      { internalType: "uint256", name: "currentBalance", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [{ internalType: "address", name: "volunteer", type: "address" }], name: "getVolunteerReputation", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }], name: "getRoleAdmin", outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }, { internalType: "address", name: "account", type: "address" }], name: "grantRole", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }, { internalType: "address", name: "account", type: "address" }], name: "hasRole", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "impactToken", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "bytes32", name: "eventId", type: "bytes32" }], name: "isEventProcessed", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "string", name: "nonce", type: "string" }], name: "isNonceUsed", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "minImpactScoreToRelease", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "oracleAddress", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "pause", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "paused", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  {
    inputs: [
      { internalType: "bytes32", name: "eventId", type: "bytes32" },
      { internalType: "address", name: "volunteerAddress", type: "address" },
      { internalType: "address", name: "beneficiaryAddress", type: "address" },
      { internalType: "uint256", name: "impactScoreScaled", type: "uint256" },
      { internalType: "uint256", name: "tokenRewardWei", type: "uint256" },
      { internalType: "bytes32", name: "zkProofHash", type: "bytes32" },
      { internalType: "bytes32", name: "eventHash", type: "bytes32" },
      { internalType: "string", name: "nonce", type: "string" },
      { internalType: "uint256", name: "expiresAt", type: "uint256" },
      { internalType: "uint8", name: "v", type: "uint8" },
      { internalType: "bytes32", name: "r", type: "bytes32" },
      { internalType: "bytes32", name: "s", type: "bytes32" },
    ],
    name: "releaseReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }, { internalType: "address", name: "callerConfirmation", type: "address" }], name: "renounceRole", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }, { internalType: "address", name: "account", type: "address" }], name: "revokeRole", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "newOracle", type: "address" }], name: "setOracleAddress", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "newMin", type: "uint256" }], name: "setMinImpactScore", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }], name: "supportsInterface", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "totalEventsVerified", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "totalFundsDeposited", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "totalFundsDistributed", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "unpause", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "vaultBalance", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "", type: "address" }], name: "donorDeposits", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "reputationLedger", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "stablecoin", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { stateMutability: "payable", type: "receive" },
] as const;

// ── ReputationLedger ABI ──────────────────────────────────────────────────────
export const REPUTATION_LEDGER_ABI = [
  {
    inputs: [{ internalType: "address", name: "admin", type: "address" }],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AccessControlBadConfirmation", type: "error" },
  { inputs: [{ internalType: "address", name: "account", type: "address" }, { internalType: "bytes32", name: "neededRole", type: "bytes32" }], name: "AccessControlUnauthorizedAccount", type: "error" },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "volunteer", type: "address" }, { indexed: false, internalType: "uint256", name: "timestamp", type: "uint256" }],
    name: "LeaderboardEntryAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "volunteer", type: "address" }, { indexed: false, internalType: "uint256", name: "scoreDelta", type: "uint256" }, { indexed: false, internalType: "uint256", name: "newCumulativeScore", type: "uint256" }, { indexed: false, internalType: "uint256", name: "eventCount", type: "uint256" }, { indexed: false, internalType: "uint256", name: "timestamp", type: "uint256" }],
    name: "ReputationUpdated",
    type: "event",
  },
  { inputs: [], name: "DEFAULT_ADMIN_ROLE", outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "VAULT_ROLE", outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }], stateMutability: "view", type: "function" },
  {
    inputs: [],
    name: "getGlobalStats",
    outputs: [
      { internalType: "uint256", name: "participants", type: "uint256" },
      { internalType: "uint256", name: "totalScore", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "offset", type: "uint256" }, { internalType: "uint256", name: "limit", type: "uint256" }],
    name: "getLeaderboardPage",
    outputs: [
      { internalType: "address[]", name: "addresses", type: "address[]" },
      { internalType: "uint256[]", name: "scores", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "getLeaderboardLength", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "volunteer", type: "address" }], name: "getBadges", outputs: [{ internalType: "uint8[]", name: "", type: "uint8[]" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "volunteer", type: "address" }, { internalType: "uint8", name: "badgeId", type: "uint8" }], name: "hasBadge", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "volunteer", type: "address" }, { internalType: "uint8", name: "badgeId", type: "uint8" }], name: "getBadgeEarnedAt", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ internalType: "address", name: "volunteer", type: "address" }],
    name: "getAllBadges",
    outputs: [{
      internalType: "struct ReputationLedger.BadgeInfo[]",
      name: "badges",
      type: "tuple[]",
      components: [
        { internalType: "uint8",   name: "id",          type: "uint8"   },
        { internalType: "string",  name: "name",        type: "string"  },
        { internalType: "string",  name: "description", type: "string"  },
        { internalType: "string",  name: "icon",        type: "string"  },
        { internalType: "uint256", name: "earnedAt",    type: "uint256" },
      ],
    }],
    stateMutability: "view",
    type: "function",
  },
  {
    type: "event",
    name: "BadgeEarned",
    inputs: [
      { indexed: true,  internalType: "address", name: "volunteer",  type: "address" },
      { indexed: true,  internalType: "uint8",   name: "badgeId",   type: "uint8"   },
      { indexed: false, internalType: "string",  name: "badgeName", type: "string"  },
      { indexed: false, internalType: "uint256", name: "timestamp", type: "uint256" },
    ],
  },
  {
    inputs: [{ internalType: "address", name: "volunteer", type: "address" }],
    name: "getReputation",
    outputs: [
      { internalType: "uint256", name: "cumulativeScore", type: "uint256" },
      { internalType: "uint256", name: "eventCount", type: "uint256" },
      { internalType: "uint256", name: "lastUpdatedAt", type: "uint256" },
      { internalType: "uint256", name: "rank", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "volunteer", type: "address" }],
    name: "getScoreHistory",
    outputs: [{ components: [{ internalType: "uint256", name: "score", type: "uint256" }, { internalType: "uint256", name: "timestamp", type: "uint256" }, { internalType: "bytes32", name: "eventHash", type: "bytes32" }], internalType: "struct ReputationLedger.ScoreEntry[]", name: "", type: "tuple[]" }],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }], name: "getRoleAdmin", outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }, { internalType: "address", name: "account", type: "address" }], name: "grantRole", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }, { internalType: "address", name: "account", type: "address" }], name: "hasRole", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "", type: "uint256" }], name: "leaderboard", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }, { internalType: "address", name: "callerConfirmation", type: "address" }], name: "renounceRole", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }, { internalType: "address", name: "account", type: "address" }], name: "revokeRole", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }], name: "supportsInterface", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "totalImpactScoreGenerated", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "totalParticipants", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ internalType: "address", name: "volunteer", type: "address" }, { internalType: "uint256", name: "scoreDelta", type: "uint256" }],
    name: "updateReputation",
    outputs: [{ internalType: "uint256", name: "newCumulative", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

// ── ImpactToken (GOOD) ABI — ERC20 + extra ───────────────────────────────────
export const IMPACT_TOKEN_ABI = [
  { inputs: [{ internalType: "address", name: "admin", type: "address" }], stateMutability: "nonpayable", type: "constructor" },
  { inputs: [{ internalType: "address", name: "spender", type: "address" }, { internalType: "uint256", name: "allowance", type: "uint256" }, { internalType: "uint256", name: "needed", type: "uint256" }], name: "ERC20InsufficientAllowance", type: "error" },
  { inputs: [{ internalType: "address", name: "sender", type: "address" }, { internalType: "uint256", name: "balance", type: "uint256" }, { internalType: "uint256", name: "needed", type: "uint256" }], name: "ERC20InsufficientBalance", type: "error" },
  { inputs: [{ internalType: "address", name: "approver", type: "address" }], name: "ERC20InvalidApprover", type: "error" },
  { inputs: [{ internalType: "address", name: "receiver", type: "address" }], name: "ERC20InvalidReceiver", type: "error" },
  { inputs: [{ internalType: "address", name: "sender", type: "address" }], name: "ERC20InvalidSender", type: "error" },
  { inputs: [{ internalType: "address", name: "spender", type: "address" }], name: "ERC20InvalidSpender", type: "error" },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "owner", type: "address" }, { indexed: true, internalType: "address", name: "spender", type: "address" }, { indexed: false, internalType: "uint256", name: "value", type: "uint256" }],
    name: "Approval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "from", type: "address" }, { indexed: false, internalType: "uint256", name: "amount", type: "uint256" }, { indexed: false, internalType: "uint256", name: "totalBurned", type: "uint256" }],
    name: "TokensBurned",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "to", type: "address" }, { indexed: false, internalType: "uint256", name: "amount", type: "uint256" }, { indexed: false, internalType: "uint256", name: "totalMinted", type: "uint256" }],
    name: "TokensMinted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "from", type: "address" }, { indexed: true, internalType: "address", name: "to", type: "address" }, { indexed: false, internalType: "uint256", name: "value", type: "uint256" }],
    name: "Transfer",
    type: "event",
  },
  { inputs: [{ internalType: "address", name: "owner", type: "address" }, { internalType: "address", name: "spender", type: "address" }], name: "allowance", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "spender", type: "address" }, { internalType: "uint256", name: "value", type: "uint256" }], name: "approve", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "account", type: "address" }], name: "balanceOf", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }], name: "burn", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "circulatingSupply", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "decimals", outputs: [{ internalType: "uint8", name: "", type: "uint8" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "to", type: "address" }, { internalType: "uint256", name: "amount", type: "uint256" }], name: "mint", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "name", outputs: [{ internalType: "string", name: "", type: "string" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "symbol", outputs: [{ internalType: "string", name: "", type: "string" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "totalSupply", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "to", type: "address" }, { internalType: "uint256", name: "value", type: "uint256" }], name: "transfer", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "from", type: "address" }, { internalType: "address", name: "to", type: "address" }, { internalType: "uint256", name: "value", type: "uint256" }], name: "transferFrom", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "nonpayable", type: "function" },
] as const;